//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by QUNO.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDB_DECK                        102
#define ID_RED_ONE                      106
#define ID_RED_TWO                      107
#define ID_RED_THREE                    108
#define ID_RED_FOUR                     109
#define ID_RED_FIVE                     110
#define ID_RED_SIX                      111
#define ID_RED_SEVEN                    112
#define ID_RED_EIGHT                    113
#define ID_RED_NINE                     114
#define ID_RED_ZERO                     115
#define ID_RED_DRAWTWO                  116
#define ID_RED_SKIP                     117
#define ID_WILD                         118
#define ID_BLUE_ZERO                    119
#define IDD_PICKCOLOR                   119
#define ID_BLUE_ONE                     120
#define ID_BLUE_TWO                     121
#define ID_BLUE_THREE                   122
#define ID_BLUE_FOUR                    123
#define ID_BLUE_DRAWTWO                 124
#define ID_BLUE_EIGHT                   125
#define ID_BLUE_FIVE                    126
#define ID_BLUE_NINE                    127
#define ID_BLUE_SEVEN                   128
#define ID_BLUE_SIX                     129
#define ID_BLUE_SKIP                    130
#define ID_GREEN_DRAWTWO                131
#define ID_GREEN_EIGHT                  132
#define ID_GREEN_FIVE                   133
#define ID_GREEN_FOUR                   134
#define ID_GREEN_NINE                   135
#define ID_GREEN_ONE                    136
#define ID_GREEN_SEVEN                  137
#define ID_GREEN_SIX                    138
#define ID_GREEN_SKIP                   139
#define ID_GREEN_THREE                  140
#define ID_GREEN_TWO                    141
#define ID_GREEN_ZERO                   142
#define ID_YELLOW_DRAWTWO               143
#define ID_YELLOW_EIGHT                 144
#define ID_YELLOW_FIVE                  145
#define ID_YELLOW_FOUR                  146
#define ID_YELLOW_NINE                  147
#define ID_YELLOW_ONE                   148
#define ID_YELLOW_SEVEN                 149
#define ID_YELLOW_SIX                   150
#define ID_YELLOW_SKIP                  151
#define ID_YELLOW_THREE                 152
#define ID_YELLOW_TWO                   153
#define ID_YELLOW_ZERO                  154
#define IDC_RED                         1000
#define IDC_BLUE                        1001
#define IDC_YELLOW                      1002
#define IDC_GREEN                       1003
#define IDC_WILDCOLOR                   1004
#define ID_NEWGAME                      32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
