//////////////////////////////////////////////////////////////////////////
// RogCorp QUno
// version 2.0
//
//        File:  stdafx.h
// Description:  header file for standard Windows system include files, 
//               or project-specific include files that are not changed frequently
//     Revised:  08/21/97
//
// Copyright © 1997 Roger Deetz

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
